services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    networks:
      - default

  backend:
    image: ghcr.io/zethange/vdeniske:backend-latest
    depends_on:
      - db
    environment:
      TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    labels:
      - "traefik.http.routers.vdeniske_backend.rule=Host(`vdeniske.ru`) && PathPrefix(`/api`)"
      - "traefik.http.routers.vdeniske_backend.middlewares=test-ratelimit"
      - "traefik.http.services.vdeniske_backend.loadbalancer.server.port=3000"
    volumes:
      - ./storage:/storage
    networks:
      - web
      - default

  static:
    image: nginx:alpine
    volumes:
      - ./storage:/storage
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.http.routers.vdeniske_static.rule=Host(`vdeniske.ru`) && PathPrefix(`/static`)"
      - "traefik.http.routers.vdeniske_static.middlewares=test-ratelimit"
    networks:
      - web

  frontend:
    image: ghcr.io/zethange/vdeniske:frontend-latest
    depends_on:
      - backend
    labels:
      - "traefik.http.routers.vdeniske_frontend.rule=Host(`vdeniske.ru`)"
      - "traefik.http.routers.vdeniske_frontend.middlewares=test-ratelimit"
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
    external: true
  default:
